### ISSUE TITLE
New Pydantic v2.0 breaks parakeet

### ISSUE THREAD

**Issue by DimitriosBellos** [rosalindfranklininstitute/parakeet#53]
In a fresh installation of parakeet I executed 
`parakeet.config.new -c config.yaml`
And I got:

Traceback (most recent call last):
  File "<miniconda-install-dir>/envs/parakeet-env/bin/parakeet.config.new", line 5, in <module>
    from parakeet.command_line.config import new
  File "<miniconda-install-dir>/envs/parakeet-env/lib/python3.9/site-packages/parakeet/__init__.py", line 19, in <module>
    from parakeet._run import run  # noqa
  File "<miniconda-install-dir>/envs/parakeet-env/lib/python3.9/site-packages/parakeet/_run.py", line 13, in <module>
    import parakeet.config
  File "<miniconda-install-dir>/envs/parakeet-env/lib/python3.9/site-packages/parakeet/config.py", line 727, in <module>
    class Config(BaseModel):
  File "<miniconda-install-dir>/envs/parakeet-env/lib/python3.9/site-packages/parakeet/config.py", line 734, in Config
    Sample(),
  File "<miniconda-install-dir>/envs/parakeet-env/lib/python3.9/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for Sample
coords
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
molecules
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
ice
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
sputter
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing

I then installed the most recent v1 version of pydantic
`pip install pydantic==1.10.10`
And it worked

Maybe you need to lock in the setup.py the pydantic version to v1.10.10 or find a way to be compatible with the new v2.0 version of pydantic

**Comment by jmp1985** [comment]
Hi @DimitriosBellos 

Yes, I saw this yesterday. It seems that many packages are broken by this change. I will have a look at fixing it today.

Best wishes
James
